### ISSUE TITLE
Deploying with gulp fails

### ISSUE THREAD

**Issue by Boscop** [StartPolymer/polymer-starter-kit-plus#54]
I downloaded the zip of the master and followed the steps in the Readme.
Using the Git Shell on Windows 8.1.
```
D:\3rdparty\polymer-starter-kit-plus> gulp deploy:dev
fatal: Not a git repository (or any of the parent directories): .git
Warning: Can't run "git describe" for determine app version
[22:29:42] Using gulpfile D:\3rdparty\polymer-starter-kit-plus\gulpfile.js
[22:29:42] Starting 'pre-deploy'...
[22:29:42] Starting 'clean'...
[22:29:42] Finished 'clean' after 6.63 ms
[22:29:42] Starting 'default'...
[22:29:42] 'default' errored after 124 μs
[22:29:42] Error: Task manifest is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').use(gulp).
    at D:\3rdparty\polymer-starter-kit-plus\node_modules\run-sequence\index.js:20:10
    at Array.forEach (native)
    at verifyTaskSets (D:\3rdparty\polymer-starter-kit-plus\node_modules\run-sequence\index.js:13:11)
    at D:\3rdparty\polymer-starter-kit-plus\node_modules\run-sequence\index.js:32:4
    at Array.forEach (native)
    at verifyTaskSets (D:\3rdparty\polymer-starter-kit-plus\node_modules\run-sequence\index.js:13:11)
    at runSequence (D:\3rdparty\polymer-starter-kit-plus\node_modules\run-sequence\index.js:92:2)
    at Gulp.<anonymous> (D:\3rdparty\polymer-starter-kit-plus\gulpfile.js:321:3)
    at module.exports (D:\3rdparty\polymer-starter-kit-plus\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\3rdparty\polymer-starter-kit-plus\node_modules\orchestrator\index.js:273:3)
[22:29:42] 'pre-deploy' errored after 11 ms
[22:29:42] Error in plugin 'run-sequence(default)'
Message:
    Task manifest is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequenc
e').use(gulp).
Stack:
Error: Task manifest is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').use(gulp).
    at D:\3rdparty\polymer-starter-kit-plus\node_modules\run-sequence\index.js:20:10
    at Array.forEach (native)
    at verifyTaskSets (D:\3rdparty\polymer-starter-kit-plus\node_modules\run-sequence\index.js:13:11)
    at D:\3rdparty\polymer-starter-kit-plus\node_modules\run-sequence\index.js:32:4
    at Array.forEach (native)
    at verifyTaskSets (D:\3rdparty\polymer-starter-kit-plus\node_modules\run-sequence\index.js:13:11)
    at runSequence (D:\3rdparty\polymer-starter-kit-plus\node_modules\run-sequence\index.js:92:2)
    at Gulp.<anonymous> (D:\3rdparty\polymer-starter-kit-plus\gulpfile.js:321:3)
    at module.exports (D:\3rdparty\polymer-starter-kit-plus\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\3rdparty\polymer-starter-kit-plus\node_modules\orchestrator\index.js:273:3)
```

I also tried with 
```js
var runSequence = require('run-sequence').use(gulp);
```
but it gave the same error.
What am I doing wrong?

**Comment by dtodt** [comment]
+1

I'm with the same problem.
It seems to be the **manifest** task that was removed on **Pull Request 39**.

I've tried two approaches:
1) I removed the _manifest_ call from _default_ task.
With that, the app runs ok, but the manifest is not moved into _dist_ folder.
The browser cant identify the app name and icon.

2) I reversed the removal of the _manifest_ task.
With that, the app runs ok, and the manifest is moved into _dist_ folder, but the properties _appName_ and _appShortName_ are not converted.
The browser can identify the app manifest, but de name is **{$ appName $}**.

**Comment by Boscop** [comment]
Isn't there a way to have the cake and eat it too?
Manifest to dist and substituted `appName`?

**Comment by dtodt** [comment]
I did not understand how it can find **theme.manifest.themeColor**, but not **appName**, I've even failed on identify where _theme.manifest.themeColor_ is set.

I've tried to put an attribute called 'app_name' inside **variables.manifest** object, but it does not work.

It would be nice if some of the developers solved this doubt.
